"""Add enums for topics

Revision ID: cd64c8124fac
Revises: 1a31ce608336
Create Date: 2025-05-06 20:29:52.185124

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd64c8124fac'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # Create the enum type
    sa.Enum(
        'HISTORY', 'GEOGRAPHY', 'TECHNOLOGY', 'GENERAL', 'ART', 'MUSIC',
        'LITERATURE', 'SOCIOLOGY', 'PHILOSOPHY', 'PHYSICS', 'CHEMISTRY',
        'BIOLOGY', 'MATHEMATICS', name='topictype_enum'
    ).create(op.get_bind())

    # Remove the existing default value
    op.execute("ALTER TABLE item ALTER COLUMN topic DROP DEFAULT")

    # Alter the column type to the new enum
    op.alter_column(
        'item', 'topic',
        existing_type=sa.VARCHAR(length=255),
        type_=postgresql.ENUM(
            'HISTORY', 'GEOGRAPHY', 'TECHNOLOGY', 'GENERAL', 'ART', 'MUSIC',
            'LITERATURE', 'SOCIOLOGY', 'PHILOSOPHY', 'PHYSICS', 'CHEMISTRY',
            'BIOLOGY', 'MATHEMATICS', name='topictype_enum'
        ),
        nullable=True,
        postgresql_using='topic::topictype_enum'
    )

    # Reapply the default value
    op.execute("ALTER TABLE item ALTER COLUMN topic SET DEFAULT 'GENERAL'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'topic',
               existing_type=postgresql.ENUM('HISTORY', 'GEOGRAPHY', 'TECHNOLOGY', 'GENERAL', 'ART', 'MUSIC', 'LITERATURE', 'SOCIOLOGY', 'PHILOSOPHY', 'PHYSICS', 'CHEMISTRY', 'BIOLOGY', 'MATHEMATICS', name='topictype_enum'),
               type_=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'general'::character varying"))
    sa.Enum('HISTORY', 'GEOGRAPHY', 'TECHNOLOGY', 'GENERAL', 'ART', 'MUSIC', 'LITERATURE', 'SOCIOLOGY', 'PHILOSOPHY', 'PHYSICS', 'CHEMISTRY', 'BIOLOGY', 'MATHEMATICS', name='topictype_enum').drop(op.get_bind())
    # ### end Alembic commands ###
